#!/usr/bin/env python3

import sys
from pathlib import Path
import pandas as pd
import numpy as np
from ordered_set import OrderedSet
from rich import print
from matplotlib import pyplot as plt


def getMarks(df: pd.DataFrame) -> pd.DataFrame:

    sid = 'شناسه کاربری'
    sname = 'نام و نام خانوادگی'
    sgrade = 'نمره داوری با تاخیر'

    major_header = list(OrderedSet([f for f, s in df.columns]))
    minor_header = list(OrderedSet([s for f, s in df.columns]))
    minor_header = [sid] + [sgrade] * (len(major_header) - 1)
    headers = pd.MultiIndex.from_tuples(list(zip(major_header, minor_header)))
    ndf = df[headers]
    ndf.columns = [
        col.replace('سوال ', '') for col in minor_header[:1] + major_header[1:]
    ]
    ndf = ndf.fillna(0)
    ndf = ndf.drop(ndf.loc[ndf[ndf.columns[0]] == 0].index)
    ndf[ndf.columns[0]] = ndf[ndf.columns[0]].astype('str')  #uint64')
    for i in range(1, len(headers)):
        ndf[ndf.columns[i]] = ndf[ndf.columns[i]].astype('uint8')
    ndf = ndf.set_index(ndf.columns[0])
    return ndf.groupby(level=0).sum()

colors = ['#f7fbff', '#deebf7', '#c6dbef',
        '#9ecae1', '#6baed6', '#4292c6',
        '#2171b5','#08519c','#08306b'][::-1]

def plot_marks(Ys, title=''):
    fig, ax = plt.subplots()
    fig.set_figheight(4)
    fig.set_figwidth(16)
    for i,y in enumerate(Ys[:-1]):
        ax.plot(y.index, y, color=colors[i%9])
    ax.plot(Ys[-1].index, Ys[-1], marker='o', color='r')
    for i, txt in enumerate(Ys[-1]):
        ax.annotate(text=txt, xy=(i + .1, txt))
    ax.set_xticks(Ys[-1].index, Ys[-1].index, rotation=55, rotation_mode='anchor', ha='right')
    ax.set_title(title)
    fig.savefig('scores.png', bbox_inches='tight')

##################################
### Accumulates all the scores ###
##################################

files = list(sorted(Path('.').glob('*xlsx')))
if files == []: 
    print('There is no xlsx file to be processed.!')
    sys.exit()

Ys = []
df = getMarks(pd.read_excel(files[0], header=[0, 1], dtype={('مشخصات کاربر','شناسه کاربری'): str,}))
for file in files[1:]:
    ndf = getMarks(pd.read_excel(file, header=[0, 1], dtype={('مشخصات کاربر','شناسه کاربری'): str,}))
    Ys.append( df.sum(axis=1).astype('uint32') )
    df = pd.concat([df, ndf], axis=1)

df['sum'] = df.sum(axis=1).astype('uint32')
Ys.append(df['sum'])

df.to_csv('total.csv')

plot_marks(Ys, title=f"Cumulative Plot for {len(files)} Assignment(s) with {len(df.columns)-1} Question(s) in Total.")

fig = plt.figure()
df['sum'].hist()
fig.savefig('hist.png', bbox_inches='tight')

print(f"\tAverage Score is: {df['sum'].sum()//len(df)} [{len(files)} Assignment(s) with {len(df.columns)-1} Question(s)]")

print(sorted(list(zip(df.index, df['sum']))))

